# Generated by Django 4.2.5 on 2023-09-13 07:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('identity_no', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Invalid Identity Number', regex='^[STFG]\\d{7}[A-Z]$')])),
                ('address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
            options={
                'db_table': 'customer"."customer_info',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='customer.accounts')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='customer.accounts')),
            ],
            options={
                'db_table': 'customer"."transactions',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.accounttypes'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
