# Generated by Django 4.2.5 on 2023-09-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'type')},
        ),
    ]
