# Generated by Django 4.2.5 on 2023-09-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user.auth_user',
        ),
    ]
