# Generated by Django 4.2.5 on 2023-09-09 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff"."departments',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
            ],
            options={
                'db_table': 'staff"."staff_info',
            },
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('ticket_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.departments')),
            ],
            options={
                'db_table': 'staff"."ticket_types',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('C', 'Closed'), ('O', 'Open'), ('A', 'Approved')], max_length=1)),
                ('created_date', models.DateTimeField()),
                ('closed_date', models.DateTimeField(null=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_tickets', to='staff.staff')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='staff.staff')),
                ('ticket_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.tickettypes')),
            ],
            options={
                'db_table': 'staff"."tickets',
            },
        ),
        migrations.CreateModel(
            name='LogCalls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('action', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff"."log_calls',
            },
        ),
        migrations.CreateModel(
            name='LogAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff"."log_accounts',
            },
        ),
        migrations.CreateModel(
            name='DeptManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.departments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'db_table': 'staff"."dept_manager',
            },
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.CheckConstraint(check=models.Q(('closed_date__isnull', True), ('closed_date__gt', models.F('created_date')), _connector='OR'), name='closed_date_check'),
        ),
        migrations.AddConstraint(
            model_name='deptmanager',
            constraint=models.UniqueConstraint(fields=('department_id', 'user_id'), name='dept_manager_unique'),
        ),
        migrations.AddConstraint(
            model_name='deptmanager',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='end_date_check'),
        ),
    ]
