# Generated by Django 4.2.5 on 2023-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff"."departments',
            },
        ),
        migrations.CreateModel(
            name='DeptManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'staff"."dept_manager',
            },
        ),
        migrations.CreateModel(
            name='LogAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'staff"."log_accounts',
            },
        ),
        migrations.CreateModel(
            name='LogCalls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff"."log_calls',
            },
        ),
    ]
