# Generated by Django 4.2.5 on 2023-09-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcalls',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='LogAccount',
        ),
        migrations.DeleteModel(
            name='LogCalls',
        ),
    ]
