# Generated by Django 4.2.5 on 2023-09-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_accounts_date_created_alter_transactions_date'),
        ('staff', '0003_remove_logcalls_user_id_alter_tickets_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='customer.customer'),
        ),
    ]
