# Generated by Django 4.2.5 on 2023-09-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_tickets_closed_by_alter_tickets_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='staff.staff'),
        ),
    ]
