# Generated by Django 4.2.5 on 2023-09-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_tickets_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_type_id',
        ),
    ]
