# Generated by Django 4.2.5 on 2023-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_created_date_tickets_opened_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickets',
            name='closed_date_check',
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.CheckConstraint(check=models.Q(('closed_date__isnull', True), ('closed_date__gt', models.F('opened_date')), _connector='OR'), name='closed_date_check'),
        ),
    ]
