# Generated by Django 4.2.5 on 2023-09-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_tickets_closed_date_check_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
