# Generated by Django 4.2.5 on 2023-09-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_accounts_date_created_alter_transactions_date'),
        ('staff', '0013_delete_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('C', 'Closed'), ('O', 'Open'), ('A', 'Approved')], max_length=1)),
                ('opened_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(null=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_by', to='staff.staff')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_by', to='customer.customer')),
            ],
            options={
                'db_table': 'staff"."tickets',
            },
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.CheckConstraint(check=models.Q(('closed_date__isnull', True), ('closed_date__gt', models.F('opened_date')), _connector='OR'), name='closed_date_check'),
        ),
    ]
