# Generated by Django 4.2.5 on 2023-09-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_accounts_date_created_alter_transactions_date'),
        ('staff', '0014_tickets_tickets_closed_date_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='account_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.accounttypes'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('O', 'Open'), ('A', 'Approved')], max_length=1),
        ),
    ]
