name: ZAP Scan

on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://ifs4205-23s1-1-1.comp.nus.edu.sg/'
          cmd_options: '-a'
